// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package ec2

import (
	"time"

	"github.com/the-no/aws-sdk-go/aws"
	"github.com/the-no/aws-sdk-go/aws/request"
)

// createAWSEC2Instance uses the Amazon EC2 API operation
// RunInstances to wait for a condition to be met before returning.
// If the condition is not met within the max attempt window, an error will
// be returned.
func (c *EC2) createAWSEC2Instance(input *RunInstancesInput) (r aws.Referencer, attr aws.Attrabuter, err error) {

	runinstancesrequest := input
	reservation, err := RunInstances(runinstancesrequest)
	if err == nil {
		describeinstancesrequest := &DescribeInstancesInput{}
		if err := awsutil.CopyValue(describeinstancesrequest, "InstanceIds", reservation, "Instances[].InstanceId"); err != nil {
			return nil, nil, err
		}
		if err := WaitUntilInstanceRunning(describeinstancesrequest); err != nil {
			return nil, nil, err
		}

	} else {
		return nil, nil, err
	}
	startinstancesrequest := &StartInstancesInput{}
	if err := awsutil.CopyValue(startinstancesrequest, "InstanceIds", reservation, "Instances[].InstanceId"); err != nil {
		return nil, nil, err
	}
	startinstancesresult, err := StartInstances(startinstancesrequest)
	if err == nil {
		describeinstancesrequest := &DescribeInstancesInput{}
		if err := awsutil.CopyValue(describeinstancesrequest, "InstanceIds", reservation, "Instances[].InstanceId"); err != nil {
			return nil, nil, err
		}
		if err := WaitUntilInstanceRunning(describeinstancesrequest); err != nil {
			return nil, nil, err
		}

	} else {
		return nil, nil, err
	}
	return reservation, reservation, nil
}

// deleteAWSEC2Instance uses the Amazon EC2 API operation
// TerminateInstances to wait for a condition to be met before returning.
// If the condition is not met within the max attempt window, an error will
// be returned.
func (c *EC2) deleteAWSEC2Instance(input *TerminateInstancesInput) (err error) {

	terminateinstancesrequest := input
	terminateinstancesresult, err := TerminateInstances(terminateinstancesrequest)
	if err == nil {
		describeinstancesrequest := &DescribeInstancesInput{}
		if err := awsutil.CopyValue(describeinstancesrequest, "InstanceIds", terminateinstancesrequest, "InstanceIds[]"); err != nil {
			return err
		}
		if err := WaitUntilInstanceTerminated(describeinstancesrequest); err != nil {
			return err
		}

	} else {
		return err
	}
	return nil
}
